#ifndef EMBEDDEDHELPERLIBRARY_EMPTY_BASE_CLASS_OPTIMISATION_H
#define EMBEDDEDHELPERLIBRARY_EMPTY_BASE_CLASS_OPTIMISATION_H

#if defined(_MSC_VER) && _MSC_VER >= 1910
#define EBCO __declspec(empty_bases)
#else
#define EBCO
#endif

#endif  // EMBEDDEDHELPERLIBRARY_EMPTY_BASE_CLASS_OPTIMISATION_H
