version: "{build}"

os: Visual Studio 2017

clone_folder: c:\projects\EmbeddedHelperLibrary

platform: x64
configuration: Release

before_build:
  - cd c:\projects\EmbeddedHelperLibrary
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - echo Running cmake...
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: build\EmbeddedHelperLibrary.sln

after_build:
  - cd c:\projects\EmbeddedHelperLibrary\build\test\Release
  - ehl.tests.exe
