#ifndef EMBEDDEDHELPERLIBRARY_TYPE_TRAITS_DECLVAL_H
#define EMBEDDEDHELPERLIBRARY_TYPE_TRAITS_DECLVAL_H

namespace ehl
{
	template <typename T>
	T&& declval();
}

#endif  // EMBEDDEDHELPERLIBRARY_TYPE_TRAITS_DECLVAL_H
